version: "2.1"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    hostname: postgresql
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - DB_HOST=postgresql
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data: